[tool.poetry]
name = "bqp-database-access"
version = "0.1.0"
description = ""
authors = ["Martin Ruefenacht <martin.ruefenacht@lrz.de>"]
readme = "README.md"
packages = [{include = "bqp_database_access"}]

[tool.poetry.dependencies]
python = "~3.10"
pony = "^0.7"
bcrypt = "^4.0"
psycopg2-binary = "^2.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
