[project]
name = "bqp-database-access"
version = "0.1.7"
description = ""
authors = [
    {name = "Martin Ruefenacht", email = "martin.ruefenacht@lrz.de"},
]
dependencies = [
    "pony>=0.7.16",
    "bcrypt>=4.0.1",
    "psycopg2-binary>=2.9.6",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

